obstacle_range: 3.0 #3.0
raytrace_range: 3.5 #3.5
track_unknown_space: true
map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}